name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm ci
    - name: Wait for PostgreSQL to become ready
      run: until pg_isready -h localhost -p 5432; do sleep 1; done
    - name: Set up Database
      run: |
        PGPASSWORD=admin psql -h localhost -U admin -d testdb -a -f migrations/001-init-schema.sql
        PGPASSWORD=admin psql -h localhost -U admin -d testdb -a -f migrations/002-seed-data.sql
    - run: npm test
