name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Wait for PostgreSQL to start
        run: until pg_isready -h localhost -p 5432; do sleep 1; done
      
      - name: Set up Database
        env:
          PGHOST: localhost
          PGUSER: ${{ secrets.POSTGRES_USER }}
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PGDATABASE: ${{ secrets.POSTGRES_DB }}
        run: |
          psql -d ${{ secrets.POSTGRES_DB }} -f migrations/001-init-schema.sql
          psql -d ${{ secrets.POSTGRES_DB }} -f migrations/002-seed-data.sql

      - name: Run Build
        run: npm run build --if-present

      - name: Run Tests
        env:
          DATABASE_URL: postgres://$PGUSER:$PGPASSWORD@localhost:5432/$PGDATABASE
        run: npm test
